from math import pi

PLUGIN_ID = "freebird_curve_editor"
PLUGIN_NAME = "Freebird Curve Editor"
PLUGIN_VERSION = (0, 1, 1)

SUPPORTED_FREEBIRD_VERSION = (2, 14, 2)
SUPPORTED_FREEBIRD_COMMIT = "dd3cb84"

JOYSTICK_DEADZONE = 0.15
JOYSTICK_RADIUS_RATE = 1.6
POINT_RADIUS_MIN = 0.001
POINT_RADIUS_MAX = 1000.0
DRAW_RADIUS_MIN = 0.05
DRAW_RADIUS_MAX = 20.0
DRAW_RADIUS_STEP = 1.25
MAX_TILT = 120.0 * pi
MAX_CONTROLLER_ROTATION_DELTA = 0.25 * pi
